### ISSUE TITLE
main domain issue 

### ISSUE THREAD

**Issue by connecticus** [refinerycms-contrib/refinerycms-multisites#2]
Hi Brice,
first of all thank you for great work,

I am successfully used subdomain functionality but can't figure out how to use main domain.
In other words:
subdomain.example.com - works 
but with 
example.com I am got error - 'The tenant public cannot be found.'

I will appreciate any hints.

**Comment by bricesanchez** [comment]
Hi @connecticus,

Thanks for your feedback! 

That's a good question, i currently use this extension with subdomains only. 
Because it use `Apartment` gem, we should be able to find a solution if there is a bug. 

But first of all we should create failling specs.

FYI, i use this extension with the Rest API in order to use Refinery as a API-first CMS

**Comment by connecticus** [comment]
Main domain used DB named "public", so in my case I just renamed production.sqlite3 to public.sqlite3.

Thank you @bricesanchez I appreciate your cooperation.
